# -*- coding: utf-8 -*-
# config.yaml
# Configuration file for seisplot.py

# Traces per inch   (less -> bigger plot)
tpi: 50

# Inches per second (more -> bigger plot)
ips: 2

# Wiggle skips (1 -> no skips, 2 -> every 2nd trace, etc.)
skip: 2

# Multiplication factor for amplitudes 
gain: 1 

# Fontsize
fontsize: 10

# Opacity, 0 (transparent) to 1 (black)
opacity: 0.5
